# Generated by Django 5.1.3 on 2025-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadith_id', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('text_without_tashkeel', models.TextField(blank=True, null=True)),
                ('book_name', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.CharField(blank=True, max_length=50, null=True)),
                ('exporter', models.CharField(blank=True, max_length=255, null=True)),
                ('narrators', models.JSONField(blank=True, null=True)),
                ('url', models.URLField()),
                ('is_embedded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['hadith_id'], name='Hadith_hadi_hadith__c50e00_idx'), models.Index(fields=['book_name'], name='Hadith_hadi_book_na_4e0c67_idx'), models.Index(fields=['is_embedded'], name='Hadith_hadi_is_embe_c95102_idx')],
            },
        ),
    ]
